version: 2
jobs:
   build:
     docker:
       - image: node:16.14.2
     steps:
       - checkout
       - run:
           name: Install dependencies
           command: npm install
       - run:
           name: Running lint
           command: npm run lint
       - run:
           name: Running tests
           command: npm run test
